/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nexuscomponentdeployer;

import java.io.File;
import java.util.List;

public class App {

    public static void main(String[] args) throws Exception {
        
        // 01. select files needed for packaging
        // File pom = new File("/Users/electronyoon/Downloads/seleniumProject/pom.xml");
        File pom = new File("pom.xml");
        File mavenHome = new File("./");
        File mvnw = new File("mvnw");
        
        // 02. download dependencies
        DependencyDownloader dd = new DependencyDownloader();
        int exitCode = dd.getDependenciesFromPomFile(pom, mavenHome, mvnw);
        if (exitCode != 0) {
            return;
        }
        
        // 03. create jar
        JarCreator jc = new JarCreator("myjar.jar");
        jc.setManifest();
        jc.create();
        jc.addJars();
        jc.addCompiledClasses(List.of("AppForDeployer", "HttpPostMultipart"));
        jc.finish();
    
    }
}
